spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: root
    # The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
    # DEPRECATED = com.mysql.jdbc.Driver , The new driver class is `com.mysql.cj.jdbc.Driver'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect